version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: iot_data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  mqtt-kafka-bridge:
    build:
      context: ./mqtt-kafka-bridge
    depends_on:
      - kafka
      - mosquitto

  spark:
    build:
      context: ./spark
    depends_on:
      - kafka
    environment:
      - PYSPARK_PYTHON=python
    ports:
      - "8888:8888"
  mqtt-producer:
    build:
      context: ./mqtt-producer
    container_name: mqtt-producer
    depends_on:
      - mosquitto
    volumes:
      - ./mqtt-producer:/app
    working_dir: /app
    command: python producer.py
volumes:
  influxdb-data: