apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: iot_data
    user: iot_user
    password: iot_password
    isDefault: true
    jsonData:
      httpMode: GET
    secureJsonData: {}